app.controller("rootController",function($scope,$http,$location,$timeout,$rootScope,schemaService,session)
{
	schemaService.init(function()
	{
		session.load(function()
		{
			$scope.$broadcast('ready');
		});
	});
});